version: "3.9"

services:
  postgres:
    image: postgres:15.2
    container_name: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_PORT: 5432
      POSTGRES_DB: "tinyurl"
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  migrations:
    image: migrate/migrate:4
    container_name: migrations
    volumes:
      - ./internal/tinyURL/migrations:/migrations
    command: [ "-path", "/migrations", "-database",  "postgres://postgres:password@postgres:5432/tinyurl?sslmode=disable", "up"]
    depends_on:
      postgres:
        condition: service_healthy

  tinyurl:
    container_name: tinyurl
    environment:
      DB: "postgres://postgres:pass@postgres:5432/tinyurl?sslmode=disable"
      BASE_URL: "http://timofei.com/"
    ports:
      - "5555:5555"
    build:
      context: .
      dockerfile: cmd/tinyURL/Dockerfile
    command: ${IN_MEM}
    depends_on:
      postgres:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully

