name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Download Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20
      
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        
      - name: Get dependencies
        run: |
          go mod tidy
    
      - name: Build
        run: go build cmd/tinyURL/main.go

      - name: Tests
        run: |
          go test ./... -v -coverpkg=./... -coverprofile=cover.out.tmp 
          cat cover.out.tmp | grep -v "mock.go" | grep -v "pb.go" > cover.out
          go tool cover -func=cover.out
