name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.20
      - uses: actions/checkout@v3
      - run: |
          go test ./... -v -coverpkg=./... -coverprofile=cover.out.tmp
          cat cover.out.tmp | grep -v "mock.go" | grep -v "pb.go" > cover.out
          go tool cover -func=cover.out