name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  golangci:
    name: linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29

  tests:
    needs: golangci
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.20

    - name: tests
      run: |
        go test ./... -v -coverpkg=./... -coverprofile=cover.out.tmp 
        cat cover.out.tmp | grep -v "mock.go" | grep -v "pb.go" > cover.out
        go tool cover -func=cover.out
