// Code generated by MockGen. DO NOT EDIT.
// Source: internal/pkg/tinyURL/usecase/tinyURL.go

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIRepository is a mock of IRepository interface.
type MockIRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIRepositoryMockRecorder
}

// MockIRepositoryMockRecorder is the mock recorder for MockIRepository.
type MockIRepositoryMockRecorder struct {
	mock *MockIRepository
}

// NewMockIRepository creates a new mock instance.
func NewMockIRepository(ctrl *gomock.Controller) *MockIRepository {
	mock := &MockIRepository{ctrl: ctrl}
	mock.recorder = &MockIRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIRepository) EXPECT() *MockIRepositoryMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockIRepository) Add(fullUrl, tinyUrl string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", fullUrl, tinyUrl)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockIRepositoryMockRecorder) Add(fullUrl, tinyUrl interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockIRepository)(nil).Add), fullUrl, tinyUrl)
}

// CheckIfFullUrlExists mocks base method.
func (m *MockIRepository) CheckIfFullUrlExists(fullUrl string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckIfFullUrlExists", fullUrl)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckIfFullUrlExists indicates an expected call of CheckIfFullUrlExists.
func (mr *MockIRepositoryMockRecorder) CheckIfFullUrlExists(fullUrl interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckIfFullUrlExists", reflect.TypeOf((*MockIRepository)(nil).CheckIfFullUrlExists), fullUrl)
}

// CheckIfTinyUrlExists mocks base method.
func (m *MockIRepository) CheckIfTinyUrlExists(tinyUrl string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckIfTinyUrlExists", tinyUrl)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckIfTinyUrlExists indicates an expected call of CheckIfTinyUrlExists.
func (mr *MockIRepositoryMockRecorder) CheckIfTinyUrlExists(tinyUrl interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckIfTinyUrlExists", reflect.TypeOf((*MockIRepository)(nil).CheckIfTinyUrlExists), tinyUrl)
}

// Get mocks base method.
func (m *MockIRepository) Get(tinyUrl string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", tinyUrl)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockIRepositoryMockRecorder) Get(tinyUrl interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockIRepository)(nil).Get), tinyUrl)
}
